<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="POU_1" Id="{125bf085-345b-4d97-b9ac-6266b5141218}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU_1
VAR
	a1: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[a1 := a1+1;
]]></ST>
    </Implementation>
    <LineIds Name="POU_1">
      <LineId Id="5" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>